/**
 * =============================================================================
 * TOMO CRM - Type Definitions
 * =============================================================================
 * 
 * This file contains all TypeScript type definitions for the Tomo CRM app.
 * 
 * PRODUCTION WIRING:
 * - These types should match your Supabase table schemas
 * - User IDs will be Firebase Auth user doc references (string)
 * - Add foreign key relationships (user_id) to all user-owned entities
 * 
 * SUPABASE TABLES TO CREATE (schema to be added later):
 * - users (linked to Firebase Auth uid)
 * - contacts
 * - meetings / briefs
 * - tasks
 * - integrations (stores connection status per user)
 * - onboarding_state (or embed in users table)
 * =============================================================================
 */

/** Billing plan type - maps to Stripe product/price IDs */
export type PlanType = "individual" | "team";

/**
 * Contact entity - represents a person in the user's network
 * 
 * SUPABASE: Create `contacts` table with these fields
 * - id: uuid (primary key)
 * - user_id: string (Firebase Auth uid, foreign key)
 * - name, role, organization: text
 * - last_interaction: timestamp
 * - relationship_health: enum('hot', 'warm', 'cool')
 * - tags: text[] (Postgres array)
 * - notes: text
 * - created_at, updated_at: timestamp
 * 
 * RELATED TABLES:
 * - contact_follow_ups (contact_id, title, due, status)
 * - contact_timeline (contact_id, date, type, summary)
 */
export type Contact = {
  id: string;
  name: string;
  role: string;
  organization: string;
  lastInteraction: string;
  relationshipHealth: "hot" | "warm" | "cool";
  tags: string[];
  notes: string;
  followUps: { id: string; title: string; due: string; status: "open" | "done" }[];
  timeline: { id: string; date: string; type: string; summary: string }[];
};

/**
 * Meeting Brief - AI-generated or user-created meeting summaries
 * 
 * SUPABASE: Create `meeting_briefs` table
 * - id: uuid
 * - user_id: string (Firebase Auth uid)
 * - title: text
 * - datetime: timestamp
 * - participants: text[]
 * - summary: text (can be AI-generated)
 * - commitments: text[]
 * - calendar_event_id: text (link to Google/Microsoft calendar event)
 * 
 * TOMO AI INTEGRATION:
 * - Briefs can be auto-generated by Tomo AI from calendar events
 * - Call POST /api/tomo/generate-brief with event context
 */
export type MeetingBrief = {
  id: string;
  title: string;
  datetime: string;
  participants: string[];
  summary: string;
  commitments: string[];
};

/**
 * Task Item - follow-ups, todos, and action items
 * 
 * SUPABASE: Create `tasks` table
 * - id: uuid
 * - user_id: string (Firebase Auth uid)
 * - title: text
 * - due: timestamp
 * - bucket: enum('Overdue', 'Today', 'This week')
 * - linked_to: text (optional - contact name or meeting id reference)
 * - notes: text
 * - status: enum('open', 'done')
 * - source: enum('manual', 'ai_extracted', 'email', 'meeting')
 * 
 * TOMO AI INTEGRATION:
 * - Tasks can be auto-extracted from emails/meetings
 * - Tomo AI can suggest task prioritization
 */
export type TaskItem = {
  id: string;
  title: string;
  due: string;
  bucket: "Overdue" | "Today" | "This week";
  linkedTo?: string;
  notes?: string;
};

/**
 * Onboarding State - tracks user's integration setup progress
 * 
 * SUPABASE: Can be stored in `users` table as JSONB or separate `user_integrations` table
 * 
 * PRODUCTION INTEGRATIONS TO WIRE:
 * 
 * 1. CALENDAR (Google/Microsoft):
 *    - Use Google Calendar API or Microsoft Graph API
 *    - Store OAuth tokens securely (encrypted in Supabase or use a secrets manager)
 *    - Webhook for calendar event changes
 * 
 * 2. CONTACTS (Google/Microsoft):
 *    - Google People API or Microsoft Graph API
 *    - Sync contacts to Supabase `contacts` table
 *    - Handle merge/dedup logic
 * 
 * 3. EMAIL (Gmail/Outlook):
 *    - Gmail API or Microsoft Graph API
 *    - Use for commitment extraction (Tomo AI)
 *    - Optional historical scope: after connect, user chooses last ~6 months vs future-only
 *    - Consider privacy - only process metadata or with user consent
 * 
 * 4. SLACK:
 *    - You have: app ID, token, bot ID
 *    - Install via OAuth flow
 *    - Send recaps via Slack Web API (chat.postMessage)
 *    - Receive commands via Events API or Slash commands
 * 
 * 5. TELEGRAM:
 *    - Create bot via BotFather
 *    - Store bot token securely
 *    - Send messages via Telegram Bot API
 *    - Webhook or polling for incoming messages
 * 
 * 6. AFFINITY CRM:
 *    - Affinity API v2: https://api-docs.affinity.co/
 *    - Store API token encrypted server-side
 *    - Sync Lists, People, Companies to Supabase
 *    - Map Affinity fields to Contact type
 * 
 * 7. GOOGLE SHEETS:
 *    - Google Sheets API
 *    - OAuth via Google (same as Calendar/Contacts if using Google Workspace)
 *    - Create sheet in user's Drive, store sheet ID
 *    - Two-way sync or export-only (TBD)
 */

/** Google or Microsoft — one OAuth bundle covers mail, calendar, and contacts (V1 SRS §3.2). */
export type WorkspaceProvider = "google" | "microsoft";

/** How CRM data is supplied during onboarding. */
export type CrmImportMethod = "csv" | "affinity";

export type OnboardingState = {
  /** Single-provider bundle: Gmail/Calendar/Contacts or Outlook/Calendar/Contacts (mock: one action). */
  workspaceProvider: WorkspaceProvider | null;
  workspaceBundleConnected: boolean;
  /**
   * Optional — SRS §3.3 three-tier model: first 12 months full content, months 13–36 metadata-only.
   * If false in mock, represent forward / minimal scope until user enables in Settings.
   */
  optInHistoricalEmailIngestion: boolean;
  /** Optional — Microsoft Teams or Google Meet transcripts, meeting notes, and extracted actions (SRS §3.13). */
  optInMeetingTranscripts: boolean;
  crmImportMethod: CrmImportMethod | null;
  calendarConnected: boolean;
  contactsConnected: boolean;
  emailConnected: boolean;
  slackConnected: boolean;
  /** When Slack is connected, also push “What’s on my Radar” to Slack. */
  slackWhatsOnRadarPush: boolean;
  telegramConnected: boolean;
  telegramPhone?: string;
  affinityConnected: boolean;
  affinityListId?: string;
  affinityTokenLast4?: string;
  googleSheetsConnected: boolean;
  googleSheetsFilename?: string;
  googleSheetsAuthed?: boolean;
  contactImportUploaded: boolean;
  contactImportFilename?: string;
  contactImportRowCount?: number;
  contactImportMappingSummary?: string;
  fundStrategyUploaded: boolean;
  fundStrategyFilename?: string;
  fundStrategyText?: string;
  notifications: Record<string, { email?: boolean; slack?: boolean; telegram?: boolean; inApp?: boolean }>;
  completed: boolean;
};

const defaultOnboardingNotifications: OnboardingState["notifications"] = {
  "Morning Recaps": { email: true, slack: false, telegram: false, inApp: true },
  "Meeting Briefs": { email: true, slack: false, telegram: false, inApp: true },
  FollowUps: { email: false, slack: false, telegram: false, inApp: true },
  Escalations: { email: true, slack: false, telegram: false, inApp: true },
};

/** Default onboarding slice for `tomo-onboarding` persistence and Settings pages. */
export const defaultOnboardingState: OnboardingState = {
  workspaceProvider: null,
  workspaceBundleConnected: false,
  optInHistoricalEmailIngestion: false,
  optInMeetingTranscripts: false,
  crmImportMethod: null,
  calendarConnected: false,
  contactsConnected: false,
  emailConnected: false,
  slackConnected: false,
  slackWhatsOnRadarPush: false,
  telegramConnected: false,
  affinityConnected: false,
  googleSheetsConnected: false,
  googleSheetsAuthed: false,
  contactImportUploaded: false,
  fundStrategyUploaded: false,
  notifications: defaultOnboardingNotifications,
  completed: false,
};

/**
 * Session State - current user session (client-side)
 * 
 * PRODUCTION WIRING:
 * - Replace localStorage session with Firebase Auth
 * - On login, Firebase returns user object with uid
 * - Store uid and fetch user profile from Supabase
 * - plan comes from Stripe subscription status
 * - onboardingComplete comes from Supabase user record
 * 
 * FIREBASE AUTH SETUP:
 * - Enable Email/Password, Google, and Microsoft providers
 * - On successful auth, create/update user in Supabase
 * - Use Firebase ID token for API authentication
 */
export type SessionState = {
  email: string;
  plan: PlanType;
  onboardingComplete: boolean;
  // PRODUCTION: Add these fields
  // uid: string;           // Firebase Auth uid
  // displayName?: string;
  // photoURL?: string;
  // stripeCustomerId?: string;
};








